[package]
name = "eprint"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/rjected/eprint-api"
readme = "README.md"

[dependencies]
eprint-lib = { path = "../../eprint-lib", features = ["clap"] }

# serde
serde_json = "1.0"

# async
tokio = { version = "1.21", features = ["sync", "macros", "rt-multi-thread"] }

# misc
eyre = "0.6"
clap = { version = "4", features = ["derive", "cargo"] }
