[package]
name = "eprint"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/rjected/eprint-api"
readme = "README.md"

[dependencies]
eprint-lib = { path = "../../" }
